set(BARESIP_SOURCES
        baresip/mk/static.c

        baresip/src/account.c
        baresip/src/aucodec.c
        baresip/src/audio.c
        baresip/src/aufilt.c
        baresip/src/auframe.c
        baresip/src/aulevel.c
        baresip/src/auplay.c
        baresip/src/ausrc.c
        baresip/src/baresip.c
        baresip/src/call.c
        baresip/src/cmd.c
        baresip/src/conf.c
        baresip/src/config.c
        baresip/src/contact.c
        baresip/src/custom_hdrs.c
        baresip/src/event.c
        baresip/src/h264.c
        baresip/src/log.c
        baresip/src/mctrl.c
        baresip/src/mediadev.c
        baresip/src/menc.c
        baresip/src/message.c
        baresip/src/metric.c
        baresip/src/mnat.c
        baresip/src/module.c
        baresip/src/net.c
        baresip/src/play.c
        baresip/src/reg.c
        baresip/src/rtpext.c
        baresip/src/rtpstat.c
        baresip/src/sdp.c
        baresip/src/sipreq.c
        baresip/src/stream.c
        baresip/src/stunuri.c
        baresip/src/timestamp.c
        baresip/src/ua.c
        baresip/src/ui.c
        baresip/src/vidcodec.c
        baresip/src/video.c
        baresip/src/vidfilt.c
        baresip/src/vidisp.c
        baresip/src/vidsrc.c
        baresip/src/vidutil.c

        baresip/modules/g711/g711.c
        baresip/modules/ice/ice.c
        baresip/modules/opensles/opensles.c
        baresip/modules/opensles/player.c
        baresip/modules/opensles/recorder.c

        baresip/modules/opus/decode.c
        baresip/modules/opus/encode.c
        baresip/modules/opus/opus.c
        baresip/modules/opus/sdp.c

        baresip/modules/opus_multistream/decode.c
        baresip/modules/opus_multistream/encode.c
        baresip/modules/opus_multistream/opus_multistream.c
        baresip/modules/opus_multistream/sdp.c

        baresip/modules/stun/stun.c
        baresip/modules/turn/turn.c
        baresip/modules/uuid/uuid.c

        re/src/base64/b64.c
        re/src/conf/conf.c
        re/src/crc32/crc32.c
        re/src/dbg/dbg.c
        re/src/dns/client.c
        re/src/dns/cstr.c
        re/src/dns/dname.c
        re/src/dns/hdr.c
        re/src/dns/ns.c
        re/src/dns/rr.c
        re/src/dns/rrlist.c
        re/src/fmt/ch.c
        re/src/fmt/hexdump.c
        re/src/fmt/pl.c
        re/src/fmt/print.c
        re/src/fmt/prm.c
        re/src/fmt/regex.c
        re/src/fmt/str.c
        re/src/fmt/str_error.c
        re/src/fmt/time.c
        re/src/fmt/unicode.c
        re/src/hash/func.c
        re/src/hash/hash.c
        re/src/hmac/hmac.c
        re/src/hmac/hmac_sha1.c
        re/src/http/auth.c
        re/src/http/chunk.c
        re/src/http/client.c
        re/src/http/msg.c
        re/src/http/request.c
        re/src/http/server.c
        re/src/httpauth/basic.c
        re/src/httpauth/digest.c
        re/src/ice/cand.c
        re/src/ice/candpair.c
        re/src/ice/chklist.c
        re/src/ice/comp.c
        re/src/ice/connchk.c
        re/src/ice/icem.c
        re/src/ice/icesdp.c
        re/src/ice/icestr.c
        re/src/ice/stunsrv.c
        re/src/ice/util.c
        re/src/jbuf/jbuf.c
        re/src/list/list.c
        re/src/lock/rwlock.c
        re/src/mbuf/mbuf.c
        re/src/main/epoll.c
        re/src/main/init.c
        re/src/main/main.c
        re/src/main/method.c
        re/src/md5/md5.c
        re/src/md5/wrap.c
        re/src/mem/mem.c
        re/src/mem/secure.c
        re/src/mod/dl.c
        re/src/mod/mod.c
        re/src/mqueue/mqueue.c
        re/src/msg/ctype.c
        re/src/msg/param.c
        re/src/net/if.c
        re/src/net/net.c
        re/src/net/netstr.c
        re/src/net/rt.c
        re/src/net/sock.c
        re/src/net/sockopt.c
        re/src/net/posix/pif.c
        re/src/net/linux/rt.c
        re/src/odict/entry.c
        re/src/odict/get.c
        re/src/odict/odict.c
        re/src/odict/type.c
        re/src/rtp/fb.c
        re/src/rtp/member.c
        re/src/rtp/ntp.c
        re/src/rtp/pkt.c
        re/src/rtp/rr.c
        re/src/rtp/rtcp.c
        re/src/rtp/rtp.c
        re/src/rtp/sdes.c
        re/src/rtp/sess.c
        re/src/rtp/source.c
        re/src/sa/ntop.c
        re/src/sa/printaddr.c
        re/src/sa/pton.c
        re/src/sa/sa.c
        re/src/sdp/attr.c
        re/src/sdp/format.c
        re/src/sdp/media.c
        re/src/sdp/msg.c
        re/src/sdp/session.c
        re/src/sdp/str.c
        re/src/sdp/util.c
        re/src/sha/sha1.c
        re/src/sip/addr.c
        re/src/sip/auth.c
        re/src/sip/contact.c
        re/src/sip/cseq.c
        re/src/sip/ctrans.c
        re/src/sip/dialog.c
        re/src/sip/keepalive.c
        re/src/sip/keepalive_udp.c
        re/src/sip/msg.c
        re/src/sip/reply.c
        re/src/sip/request.c
        re/src/sip/sip.c
        re/src/sip/strans.c
        re/src/sip/transp.c
        re/src/sip/via.c
        re/src/sipevent/listen.c
        re/src/sipevent/msg.c
        re/src/sipevent/notify.c
        re/src/sipevent/subscribe.c
        re/src/sipreg/reg.c
        re/src/sipsess/accept.c
        re/src/sipsess/ack.c
        re/src/sipsess/close.c
        re/src/sipsess/connect.c
        re/src/sipsess/info.c
        re/src/sipsess/listen.c
        re/src/sipsess/modify.c
        re/src/sipsess/reply.c
        re/src/sipsess/request.c
        re/src/sipsess/sess.c
        re/src/stun/addr.c
        re/src/stun/attr.c
        re/src/stun/ctrans.c
        re/src/stun/dnsdisc.c
        re/src/stun/hdr.c
        re/src/stun/ind.c
        re/src/stun/keepalive.c
        re/src/stun/msg.c
        re/src/stun/rep.c
        re/src/stun/req.c
        re/src/stun/stun.c
        re/src/stun/stunstr.c
        re/src/sys/daemon.c
        re/src/sys/endian.c
        re/src/sys/fs.c
        re/src/sys/rand.c
        re/src/sys/sleep.c
        re/src/sys/sys.c
        re/src/tcp/tcp.c
        re/src/tcp/tcp_high.c
        re/src/telev/telev.c
        re/src/tmr/tmr.c
        re/src/turn/chan.c
        re/src/turn/perm.c
        re/src/turn/turnc.c
        re/src/udp/mcast.c
        re/src/udp/udp.c
        re/src/uri/uri.c
        re/src/uri/uric.c
        re/src/websock/websock.c

        rem/src/au/fmt.c
        rem/src/aubuf/aubuf.c
        rem/src/auconv/auconv.c
        rem/src/aufile/aufile.c
        rem/src/aufile/wave.c
        rem/src/auresamp/resamp.c
        rem/src/fir/fir.c
        rem/src/g711/g711.c
        rem/src/vid/draw.c
        rem/src/vid/fmt.c
        rem/src/vid/frame.c
        rem/src/vidconv/vconv.c)

set(BARESIP_HEADERS_DIRS
        re/include
        rem/include
        baresip/include)